version: "3.7"

services:
  flaskian:
    build:
      context: .
      dockerfile: Dockerfile
    image: ian
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaskian.rule=Host(`ianmyjer.com`)"
      - "traefik.http.routers.tls=true"
      # - "traefik.http.routers.flaskian.entrypoints=websecure"
      # - "traefik.http.routers.flaskian.entrypoints=web"
      - "traefik.http.routers.flaskian.tls.certresolver=myhttpchallenge"

networks:
  web:

