version: "3.7"

services:
  flaskian:
    build:
      context: .
      dockerfile: Dockerfile
    image: ian
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`ianmyjer.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myhttpchallenge"

networks:
  web:

